version: "3.6"
services:
  #Centos, PHP, Nginx
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../hobbyproject:/var/www/hobbyproject/

  #MySQL Service
  db:
    image: mysql:5.7.22
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./images/mysql/conf/my.cnf:/etc/mysql/my.cnf

#Volumes
volumes:
  dbdata:
    driver: local
